apiVersion: v1
kind: ConfigMap
metadata:
  name: jobmonitor-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "jobmonitor.labels" (dict "name" "config" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
data:
  DB_URL: {{ .Values.config.database.url | quote }}
  DB_POOL_SIZE: {{ .Values.config.database.poolSize | quote }}
  DB_POOL_MIN_IDLE: {{ .Values.config.database.poolMinIdle | quote }}
  KAFKA_BOOTSTRAP: {{ .Values.config.kafka.bootstrapServers | quote }}
  REDIS_HOST: {{ .Values.config.redis.host | quote }}
  REDIS_PORT: {{ .Values.config.redis.port | quote }}
  EUREKA_ENABLED: {{ .Values.config.eureka.enabled | quote }}
  EUREKA_URL: {{ .Values.config.eureka.url | quote }}
  AWS_REGION: {{ .Values.config.aws.region | quote }}
  SMTP_HOST: {{ .Values.config.smtp.host | quote }}
  SMTP_PORT: {{ .Values.config.smtp.port | quote }}
  SMTP_AUTH: {{ .Values.config.smtp.auth | quote }}
  SMTP_TLS: {{ .Values.config.smtp.tls | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}
