apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "jobmonitor.labels" (dict "name" "platform" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
