apiVersion: v1
kind: Secret
metadata:
  name: jobmonitor-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "jobmonitor.labels" (dict "name" "secrets" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secrets.database.username | quote }}
  DB_PASSWORD: {{ .Values.secrets.database.password | quote }}
  JWT_SECRET: {{ .Values.secrets.jwt.secret | quote }}
  EUREKA_USERNAME: {{ .Values.secrets.eureka.username | quote }}
  EUREKA_PASSWORD: {{ .Values.secrets.eureka.password | quote }}
