package com.jobmonitor.dbperf.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity storing index recommendations generated by the analysis engine.
 */
@Entity
@Table(name = "index_suggestions")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class IndexSuggestion {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false)
    private UUID databaseId;

    @Column(nullable = false)
    private String tenantId;

    @Column(nullable = false)
    private String tableName;

    @Column(nullable = false)
    private String columnName;

    /** The suggested CREATE INDEX DDL statement. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String suggestedDdl;

    /** Justification / reason for the suggestion. */
    @Column(columnDefinition = "TEXT")
    private String reason;

    /** Estimated performance improvement percentage. */
    @Column
    private Double estimatedImprovementPct;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private SuggestionStatus status = SuggestionStatus.PENDING;

    @CreationTimestamp
    @Column(updatable = false)
    private Instant createdAt;

    public enum SuggestionStatus {
        PENDING, APPLIED, DISMISSED
    }
}
