apply from: "$rootDir/buildSrc/spring-boot-worker.gradle"

dependencies {
    implementation project(':platform:common')
    implementation project(':platform:schema')
    
    // Email
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    
    // AWS SES + SNS for prod
    implementation 'software.amazon.awssdk:ses'
    implementation 'software.amazon.awssdk:sns'
}
